// Shared English question bank used by every game in this repo.
// Each theme has:
//   - id, name, emoji, color, unlocked
//   - words: [{ word, emoji, hint }]
//   - grammar: [{ difficulty: 1|2|3, level: 'elementary'|'junior', sentence, answer, options, hint }]
//
// Level tagging: difficulty 1 & 2 grammar (be-verbs, articles, simple
// present/continuous, this/that, some/many) is 'elementary' — appropriate
// for Grades 3-6. Difficulty 3 (comparatives, past tense, present perfect,
// future tense, modals) is 'junior' — Grades 7-9. Use forLevel() below to
// get a level-appropriate slice; raw .themes always returns the full bank.
//
// Aligned with Taiwan MOE 12-year curriculum themes for elementary &
// junior-high English (Grades 1-9).
window.QUESTION_BANK = {
    themes: [
    {
        id: 'animals', name: 'Animals', emoji: '🐾', color: '#8B4513',
        unlocked: true,
        words: [
            { word: 'cat', emoji: '🐱', hint: '貓' },
            { word: 'dog', emoji: '🐶', hint: '狗' },
            { word: 'fish', emoji: '🐟', hint: '魚' },
            { word: 'bird', emoji: '🐦', hint: '鳥' },
            { word: 'bear', emoji: '🐻', hint: '熊' },
            { word: 'frog', emoji: '🐸', hint: '青蛙' },
            { word: 'duck', emoji: '🦆', hint: '鴨子' },
            { word: 'pig', emoji: '🐷', hint: '豬' },
            { word: 'cow', emoji: '🐮', hint: '牛' },
            { word: 'rabbit', emoji: '🐰', hint: '兔子' },
            { word: 'tiger', emoji: '🐯', hint: '老虎' },
            { word: 'horse', emoji: '🐴', hint: '馬' },
            { word: 'sheep', emoji: '🐑', hint: '羊' },
            { word: 'mouse', emoji: '🐭', hint: '老鼠' },
            { word: 'snake', emoji: '🐍', hint: '蛇' },
            { word: 'lion', emoji: '🦁', hint: '獅子' },
            { word: 'monkey', emoji: '🐵', hint: '猴子' },
            { word: 'panda', emoji: '🐼', hint: '熊貓' },
        ],
        grammar: [
            { difficulty: 1, level: 'elementary', sentence: 'A cat ___ small.', answer: 'is', options: ['is', 'are', 'am'], hint: '貓很小' },
            { difficulty: 1, level: 'elementary', sentence: 'Dogs ___ friendly.', answer: 'are', options: ['is', 'are', 'am'], hint: '狗很友善' },
            { difficulty: 1, level: 'elementary', sentence: 'I ___ a bird.', answer: 'see', options: ['see', 'sees', 'saw'], hint: '我看到一隻鳥' },
            { difficulty: 1, level: 'elementary', sentence: 'The fish ___ in water.', answer: 'swims', options: ['swim', 'swims', 'swimming'], hint: '魚在水裡游' },
            { difficulty: 1, level: 'elementary', sentence: 'The frog ___ jump.', answer: 'can', options: ['can', 'is', 'are'], hint: '青蛙會跳' },
            { difficulty: 2, level: 'elementary', sentence: 'The dog is ___.', answer: 'running', options: ['run', 'runs', 'running'], hint: '狗在跑' },
            { difficulty: 2, level: 'elementary', sentence: 'There ___ many cows.', answer: 'are', options: ['is', 'are', 'am'], hint: '有很多牛' },
            { difficulty: 2, level: 'elementary', sentence: 'I have ___ pet rabbit.', answer: 'a', options: ['a', 'an', 'the'], hint: '我有一隻寵物兔' },
            { difficulty: 2, level: 'elementary', sentence: 'Look at ___ tiger!', answer: 'that', options: ['this', 'those', 'that'], hint: '看那隻老虎' },
            { difficulty: 3, level: 'junior', sentence: 'A lion is ___ than a cat.', answer: 'bigger', options: ['big', 'bigger', 'biggest'], hint: '獅子比貓大' },
            { difficulty: 3, level: 'junior', sentence: 'Yesterday I ___ a panda.', answer: 'saw', options: ['see', 'saw', 'seen'], hint: '昨天我看到熊貓' },
            { difficulty: 3, level: 'junior', sentence: 'Monkeys ___ in trees.', answer: 'live', options: ['live', 'lives', 'living'], hint: '猴子住在樹上' },
            { difficulty: 1, level: 'elementary', sentence: 'A bear ___ big.', answer: 'is', options: ["is","are","am"], hint: '熊很大' },
            { difficulty: 2, level: 'elementary', sentence: 'The ducks ___ swimming.', answer: 'are', options: ["is","are","am"], hint: '鴨子在游泳' },
            { difficulty: 2, level: 'elementary', sentence: 'I see two ___.', answer: 'rabbits', options: ["rabbit","rabbits","rabbiting"], hint: '我看到兩隻兔子' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ a horse last week.', answer: 'rode', options: ["ride","rode","ridden"], hint: '我上週騎了馬' },
            { difficulty: 3, level: 'junior', sentence: 'The lion ___ been sleeping.', answer: 'has', options: ["is","has","was"], hint: '獅子一直在睡覺' },
            { difficulty: 3, level: 'junior', sentence: 'Cats are ___ than dogs.', answer: 'smarter', options: ["smart","smarter","smartest"], hint: '貓比狗聰明' },
        ],
    },
    {
        id: 'food', name: 'Food', emoji: '🍎', color: '#E74C3C',
        unlocked: true,
        words: [
            { word: 'apple', emoji: '🍎', hint: '蘋果' },
            { word: 'rice', emoji: '🍚', hint: '飯' },
            { word: 'milk', emoji: '🥛', hint: '牛奶' },
            { word: 'egg', emoji: '🥚', hint: '蛋' },
            { word: 'bread', emoji: '🍞', hint: '麵包' },
            { word: 'cake', emoji: '🎂', hint: '蛋糕' },
            { word: 'candy', emoji: '🍬', hint: '糖果' },
            { word: 'water', emoji: '💧', hint: '水' },
            { word: 'juice', emoji: '🧃', hint: '果汁' },
            { word: 'pizza', emoji: '🍕', hint: '披薩' },
            { word: 'banana', emoji: '🍌', hint: '香蕉' },
            { word: 'orange', emoji: '🍊', hint: '橘子' },
            { word: 'cookie', emoji: '🍪', hint: '餅乾' },
            { word: 'soup', emoji: '🍲', hint: '湯' },
            { word: 'meat', emoji: '🍖', hint: '肉' },
            { word: 'cheese', emoji: '🧀', hint: '起司' },
            { word: 'noodle', emoji: '🍜', hint: '麵' },
            { word: 'salad', emoji: '🥗', hint: '沙拉' },
        ],
        grammar: [
            { difficulty: 1, level: 'elementary', sentence: 'I like ___.', answer: 'apples', options: ['apple', 'apples', 'an apple'], hint: '我喜歡蘋果' },
            { difficulty: 1, level: 'elementary', sentence: 'She ___ rice.', answer: 'eats', options: ['eat', 'eats', 'eating'], hint: '她吃飯' },
            { difficulty: 1, level: 'elementary', sentence: 'I want ___ milk.', answer: 'some', options: ['a', 'some', 'many'], hint: '我想要一些牛奶' },
            { difficulty: 1, level: 'elementary', sentence: 'The cake ___ sweet.', answer: 'is', options: ['is', 'are', 'am'], hint: '蛋糕很甜' },
            { difficulty: 1, level: 'elementary', sentence: 'Do you like ___?', answer: 'pizza', options: ['pizza', 'pizzas', 'a pizza'], hint: '你喜歡披薩嗎？' },
            { difficulty: 2, level: 'elementary', sentence: 'There ___ apples on the table.', answer: 'are', options: ['is', 'are', 'am'], hint: '桌上有蘋果' },
            { difficulty: 2, level: 'elementary', sentence: 'She has ___ orange.', answer: 'an', options: ['a', 'an', 'the'], hint: '她有一顆橘子' },
            { difficulty: 2, level: 'elementary', sentence: 'We are ___ pizza now.', answer: 'eating', options: ['eat', 'eating', 'ate'], hint: '我們正在吃披薩' },
            { difficulty: 2, level: 'elementary', sentence: 'I drink ___ juice.', answer: 'some', options: ['a', 'some', 'many'], hint: '我喝一些果汁' },
            { difficulty: 3, level: 'junior', sentence: 'This cake is ___ than that one.', answer: 'sweeter', options: ['sweet', 'sweeter', 'sweetest'], hint: '這蛋糕比那個甜' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ many cookies yesterday.', answer: 'ate', options: ['eat', 'eats', 'ate'], hint: '我昨天吃很多餅乾' },
            { difficulty: 3, level: 'junior', sentence: 'How ___ apples do you have?', answer: 'many', options: ['much', 'many', 'lots'], hint: '你有多少蘋果？' },
            { difficulty: 1, level: 'elementary', sentence: 'I drink ___ water.', answer: 'some', options: ["a","some","many"], hint: '我喝一些水' },
            { difficulty: 2, level: 'elementary', sentence: 'Eggs ___ in the basket.', answer: 'are', options: ["is","are","am"], hint: '蛋在籃子裡' },
            { difficulty: 2, level: 'elementary', sentence: 'I am ___ bread.', answer: 'eating', options: ["eat","eats","eating"], hint: '我正在吃麵包' },
            { difficulty: 3, level: 'junior', sentence: 'This bread is ___ than that one.', answer: 'fresher', options: ["fresh","fresher","freshest"], hint: '這麵包比那個新鮮' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ pizza for lunch.', answer: 'had', options: ["have","has","had"], hint: '我午餐吃了披薩' },
            { difficulty: 3, level: 'junior', sentence: 'She ___ never tried sushi.', answer: 'has', options: ["is","has","have"], hint: '她從未吃過壽司' },
        ],
    },
    {
        id: 'colors', name: 'Colors', emoji: '🌈', color: '#9B59B6',
        unlocked: true,
        words: [
            { word: 'red', emoji: '🔴', hint: '紅色' },
            { word: 'blue', emoji: '🔵', hint: '藍色' },
            { word: 'green', emoji: '🟢', hint: '綠色' },
            { word: 'yellow', emoji: '🟡', hint: '黃色' },
            { word: 'pink', emoji: '🩷', hint: '粉紅色' },
            { word: 'black', emoji: '⚫', hint: '黑色' },
            { word: 'white', emoji: '⚪', hint: '白色' },
            { word: 'orange', emoji: '🟠', hint: '橘色' },
            { word: 'purple', emoji: '🟣', hint: '紫色' },
            { word: 'brown', emoji: '🟤', hint: '棕色' },
            { word: 'gold', emoji: '🥇', hint: '金色' },
            { word: 'silver', emoji: '🥈', hint: '銀色' },
            { word: 'rainbow', emoji: '🌈', hint: '彩虹' },
            { word: 'gray', emoji: '🌫️', hint: '灰色' },
        ],
        grammar: [
            { difficulty: 1, level: 'elementary', sentence: 'The sky ___ blue.', answer: 'is', options: ['is', 'are', 'am'], hint: '天空是藍色的' },
            { difficulty: 1, level: 'elementary', sentence: 'Apples ___ red.', answer: 'are', options: ['is', 'are', 'am'], hint: '蘋果是紅色的' },
            { difficulty: 1, level: 'elementary', sentence: 'I like ___ color.', answer: 'this', options: ['this', 'these', 'those'], hint: '我喜歡這個顏色' },
            { difficulty: 1, level: 'elementary', sentence: 'What color ___ it?', answer: 'is', options: ['is', 'are', 'do'], hint: '它是什麼顏色？' },
            { difficulty: 1, level: 'elementary', sentence: 'My bag is ___.', answer: 'black', options: ['a black', 'black', 'blacks'], hint: '我的包是黑色的' },
            { difficulty: 2, level: 'elementary', sentence: 'The grass is ___.', answer: 'green', options: ['red', 'green', 'yellow'], hint: '草是綠色的' },
            { difficulty: 2, level: 'elementary', sentence: 'Bananas ___ yellow.', answer: 'are', options: ['is', 'are', 'am'], hint: '香蕉是黃色的' },
            { difficulty: 2, level: 'elementary', sentence: 'I have ___ orange shirt.', answer: 'an', options: ['a', 'an', 'the'], hint: '我有一件橘色襯衫' },
            { difficulty: 2, level: 'elementary', sentence: 'Snow is ___.', answer: 'white', options: ['white', 'whites', 'a white'], hint: '雪是白色的' },
            { difficulty: 3, level: 'junior', sentence: 'Red is ___ than pink.', answer: 'darker', options: ['dark', 'darker', 'darkest'], hint: '紅色比粉紅色深' },
            { difficulty: 3, level: 'junior', sentence: 'The rainbow ___ many colors.', answer: 'has', options: ['have', 'has', 'having'], hint: '彩虹有很多顏色' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ a purple flower.', answer: 'saw', options: ['see', 'saw', 'seen'], hint: '我看到一朵紫色的花' },
            { difficulty: 1, level: 'elementary', sentence: 'The grass ___ green.', answer: 'is', options: ["is","are","am"], hint: '草是綠色的' },
            { difficulty: 2, level: 'elementary', sentence: '___ is your favorite color?', answer: 'What', options: ["What","Who","Where"], hint: '你最喜歡什麼顏色？' },
            { difficulty: 2, level: 'elementary', sentence: 'The cars ___ red.', answer: 'are', options: ["is","are","am"], hint: '車是紅色的' },
            { difficulty: 3, level: 'junior', sentence: 'Yellow is ___ than orange.', answer: 'lighter', options: ["light","lighter","lightest"], hint: '黃色比橘色淺' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ a blue bird yesterday.', answer: 'saw', options: ["see","saw","seen"], hint: '我昨天看到一隻藍鳥' },
            { difficulty: 3, level: 'junior', sentence: 'Red and yellow ___ orange.', answer: 'make', options: ["make","makes","made"], hint: '紅加黃變成橘' },
        ],
    },
    {
        id: 'family', name: 'Family', emoji: '👨‍👩‍👦', color: '#3498DB',
        unlocked: true,
        words: [
            { word: 'mom', emoji: '👩', hint: '媽媽' },
            { word: 'dad', emoji: '👨', hint: '爸爸' },
            { word: 'sister', emoji: '👧', hint: '姊妹' },
            { word: 'brother', emoji: '👦', hint: '兄弟' },
            { word: 'baby', emoji: '👶', hint: '寶寶' },
            { word: 'grandma', emoji: '👵', hint: '奶奶' },
            { word: 'grandpa', emoji: '👴', hint: '爺爺' },
            { word: 'family', emoji: '👨‍👩‍👧‍👦', hint: '家人' },
            { word: 'friend', emoji: '🤝', hint: '朋友' },
            { word: 'teacher', emoji: '👩‍🏫', hint: '老師' },
            { word: 'son', emoji: '🧒', hint: '兒子' },
            { word: 'daughter', emoji: '👧', hint: '女兒' },
            { word: 'uncle', emoji: '🧔', hint: '叔叔' },
            { word: 'aunt', emoji: '👩‍🦱', hint: '阿姨' },
            { word: 'cousin', emoji: '🧑', hint: '表親' },
            { word: 'doctor', emoji: '👨‍⚕️', hint: '醫生' },
            { word: 'student', emoji: '🧑‍🎓', hint: '學生' },
            { word: 'parent', emoji: '👫', hint: '父母' },
        ],
        grammar: [
            { difficulty: 1, level: 'elementary', sentence: 'She ___ my mom.', answer: 'is', options: ['is', 'are', 'am'], hint: '她是我媽媽' },
            { difficulty: 1, level: 'elementary', sentence: 'I love ___ dad.', answer: 'my', options: ['my', 'me', 'I'], hint: '我愛我爸爸' },
            { difficulty: 1, level: 'elementary', sentence: 'My brother ___ tall.', answer: 'is', options: ['is', 'are', 'am'], hint: '我弟弟很高' },
            { difficulty: 1, level: 'elementary', sentence: '___ is your friend?', answer: 'Who', options: ['Who', 'What', 'Where'], hint: '誰是你的朋友？' },
            { difficulty: 1, level: 'elementary', sentence: 'They ___ my family.', answer: 'are', options: ['is', 'are', 'am'], hint: '他們是我的家人' },
            { difficulty: 2, level: 'elementary', sentence: 'My sister and I ___ students.', answer: 'are', options: ['is', 'are', 'am'], hint: '我和姊姊是學生' },
            { difficulty: 2, level: 'elementary', sentence: 'My uncle ___ a doctor.', answer: 'is', options: ['is', 'are', 'am'], hint: '我叔叔是醫生' },
            { difficulty: 2, level: 'elementary', sentence: '___ are my parents.', answer: 'These', options: ['This', 'These', 'That'], hint: '這些是我的父母' },
            { difficulty: 2, level: 'elementary', sentence: 'My baby brother ___ crying.', answer: 'is', options: ['is', 'are', 'am'], hint: '我的小弟在哭' },
            { difficulty: 3, level: 'junior', sentence: 'Grandma is ___ than mom.', answer: 'older', options: ['old', 'older', 'oldest'], hint: '奶奶比媽媽老' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ my cousin yesterday.', answer: 'met', options: ['meet', 'met', 'meets'], hint: '我昨天遇到表親' },
            { difficulty: 3, level: 'junior', sentence: 'My family ___ in Taipei.', answer: 'lives', options: ['live', 'lives', 'living'], hint: '我家住在台北' },
            { difficulty: 1, level: 'elementary', sentence: 'This is ___ family.', answer: 'my', options: ["me","my","I"], hint: '這是我家人' },
            { difficulty: 2, level: 'elementary', sentence: 'My grandpa ___ kind.', answer: 'is', options: ["is","are","am"], hint: '我爺爺很善良' },
            { difficulty: 2, level: 'elementary', sentence: '___ are my friends.', answer: 'Those', options: ["That","Those","This"], hint: '那些是我的朋友' },
            { difficulty: 3, level: 'junior', sentence: 'My sister is ___ than me.', answer: 'taller', options: ["tall","taller","tallest"], hint: '我姊姊比我高' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ my grandma last weekend.', answer: 'visited', options: ["visit","visited","visiting"], hint: '我上週末探望奶奶' },
            { difficulty: 3, level: 'junior', sentence: 'My family ___ travel next year.', answer: 'will', options: ["will","was","were"], hint: '我們家明年要旅行' },
        ],
    },
    {
        id: 'school', name: 'School', emoji: '🏫', color: '#2ECC71',
        unlocked: true,
        words: [
            { word: 'book', emoji: '📖', hint: '書' },
            { word: 'pen', emoji: '🖊️', hint: '筆' },
            { word: 'desk', emoji: '🪑', hint: '書桌' },
            { word: 'bag', emoji: '🎒', hint: '書包' },
            { word: 'ruler', emoji: '📏', hint: '尺' },
            { word: 'eraser', emoji: '🧽', hint: '橡皮擦' },
            { word: 'paper', emoji: '📄', hint: '紙' },
            { word: 'pencil', emoji: '✏️', hint: '鉛筆' },
            { word: 'clock', emoji: '🕐', hint: '時鐘' },
            { word: 'map', emoji: '🗺️', hint: '地圖' },
            { word: 'chair', emoji: '💺', hint: '椅子' },
            { word: 'crayon', emoji: '🖍️', hint: '蠟筆' },
            { word: 'notebook', emoji: '📓', hint: '筆記本' },
            { word: 'scissors', emoji: '✂️', hint: '剪刀' },
            { word: 'school', emoji: '🏫', hint: '學校' },
            { word: 'globe', emoji: '🌍', hint: '地球儀' },
            { word: 'art', emoji: '🎨', hint: '美術' },
            { word: 'music', emoji: '🎵', hint: '音樂' },
        ],
        grammar: [
            { difficulty: 1, level: 'elementary', sentence: 'This ___ a book.', answer: 'is', options: ['is', 'are', 'am'], hint: '這是一本書' },
            { difficulty: 1, level: 'elementary', sentence: 'I have ___ pen.', answer: 'a', options: ['a', 'an', 'the'], hint: '我有一支筆' },
            { difficulty: 1, level: 'elementary', sentence: '___ is my bag.', answer: 'That', options: ['That', 'Those', 'These'], hint: '那是我的書包' },
            { difficulty: 1, level: 'elementary', sentence: 'There ___ two desks.', answer: 'are', options: ['is', 'are', 'am'], hint: '有兩張桌子' },
            { difficulty: 1, level: 'elementary', sentence: 'I ___ a student.', answer: 'am', options: ['is', 'are', 'am'], hint: '我是學生' },
            { difficulty: 2, level: 'elementary', sentence: 'The clock ___ on the wall.', answer: 'is', options: ['is', 'are', 'am'], hint: '時鐘在牆上' },
            { difficulty: 2, level: 'elementary', sentence: 'I need ___ eraser.', answer: 'an', options: ['a', 'an', 'the'], hint: '我需要一個橡皮擦' },
            { difficulty: 2, level: 'elementary', sentence: 'There ___ many books.', answer: 'are', options: ['is', 'are', 'am'], hint: '有很多書' },
            { difficulty: 2, level: 'elementary', sentence: 'We are ___ in class.', answer: 'reading', options: ['read', 'reads', 'reading'], hint: '我們在課堂上閱讀' },
            { difficulty: 3, level: 'junior', sentence: 'The map is ___ than the book.', answer: 'bigger', options: ['big', 'bigger', 'biggest'], hint: '地圖比書大' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ my pencil yesterday.', answer: 'lost', options: ['lose', 'lost', 'losing'], hint: '我昨天弄丟鉛筆' },
            { difficulty: 3, level: 'junior', sentence: '___ books are on the desk.', answer: 'Those', options: ['That', 'This', 'Those'], hint: '那些書在桌上' },
            { difficulty: 1, level: 'elementary', sentence: 'The book ___ on the desk.', answer: 'is', options: ["is","are","am"], hint: '書在桌上' },
            { difficulty: 2, level: 'elementary', sentence: 'I ___ to school by bus.', answer: 'go', options: ["go","goes","going"], hint: '我搭公車上學' },
            { difficulty: 2, level: 'elementary', sentence: '___ is your teacher?', answer: 'Who', options: ["What","Who","Where"], hint: '誰是你的老師？' },
            { difficulty: 3, level: 'junior', sentence: 'The notebook is ___ than the book.', answer: 'thinner', options: ["thin","thinner","thinnest"], hint: '筆記本比書薄' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ my homework yesterday.', answer: 'did', options: ["do","did","done"], hint: '我昨天做了功課' },
            { difficulty: 3, level: 'junior', sentence: 'We ___ been in school for six years.', answer: 'have', options: ["have","has","had"], hint: '我們上學六年了' },
        ],
    },
    {
        id: 'feelings', name: 'Feelings', emoji: '😊', color: '#F39C12',
        unlocked: true,
        words: [
            { word: 'happy', emoji: '😊', hint: '開心' },
            { word: 'sad', emoji: '😢', hint: '傷心' },
            { word: 'angry', emoji: '😠', hint: '生氣' },
            { word: 'tired', emoji: '😴', hint: '累' },
            { word: 'hungry', emoji: '🤤', hint: '餓' },
            { word: 'scared', emoji: '😨', hint: '害怕' },
            { word: 'brave', emoji: '💪', hint: '勇敢' },
            { word: 'hot', emoji: '🥵', hint: '熱' },
            { word: 'cold', emoji: '🥶', hint: '冷' },
            { word: 'sleepy', emoji: '😪', hint: '想睡' },
            { word: 'excited', emoji: '🤩', hint: '興奮' },
            { word: 'bored', emoji: '😑', hint: '無聊' },
            { word: 'sick', emoji: '🤒', hint: '生病' },
            { word: 'worried', emoji: '😟', hint: '擔心' },
            { word: 'sorry', emoji: '🙏', hint: '抱歉' },
            { word: 'proud', emoji: '😎', hint: '驕傲' },
            { word: 'surprised', emoji: '😲', hint: '驚訝' },
            { word: 'calm', emoji: '😌', hint: '平靜' },
        ],
        grammar: [
            { difficulty: 1, level: 'elementary', sentence: 'I ___ happy.', answer: 'am', options: ['is', 'are', 'am'], hint: '我很開心' },
            { difficulty: 1, level: 'elementary', sentence: 'She ___ tired.', answer: 'is', options: ['is', 'are', 'am'], hint: '她很累' },
            { difficulty: 1, level: 'elementary', sentence: 'Are you ___?', answer: 'hungry', options: ['hunger', 'hungry', 'hungries'], hint: '你餓了嗎？' },
            { difficulty: 1, level: 'elementary', sentence: 'We ___ not scared.', answer: 'are', options: ['is', 'are', 'am'], hint: '我們不害怕' },
            { difficulty: 1, level: 'elementary', sentence: 'He feels ___.', answer: 'cold', options: ['cold', 'colds', 'coldy'], hint: '他覺得冷' },
            { difficulty: 2, level: 'elementary', sentence: 'The kids ___ excited.', answer: 'are', options: ['is', 'are', 'am'], hint: '孩子們很興奮' },
            { difficulty: 2, level: 'elementary', sentence: 'I am very ___ today.', answer: 'happy', options: ['happy', 'happily', 'happiness'], hint: '我今天很開心' },
            { difficulty: 2, level: 'elementary', sentence: 'He ___ feeling sick.', answer: 'is', options: ['is', 'are', 'am'], hint: '他覺得不舒服' },
            { difficulty: 2, level: 'elementary', sentence: 'They look ___.', answer: 'bored', options: ['bore', 'bored', 'boring'], hint: '他們看起來很無聊' },
            { difficulty: 3, level: 'junior', sentence: 'I am ___ than yesterday.', answer: 'happier', options: ['happy', 'happier', 'happiest'], hint: '我比昨天更開心' },
            { difficulty: 3, level: 'junior', sentence: 'She ___ sad last night.', answer: 'was', options: ['is', 'was', 'were'], hint: '她昨晚很傷心' },
            { difficulty: 3, level: 'junior', sentence: 'Why ___ you worried?', answer: 'are', options: ['is', 'are', 'am'], hint: '你為什麼擔心？' },
            { difficulty: 1, level: 'elementary', sentence: 'The baby ___ sleepy.', answer: 'is', options: ["is","are","am"], hint: '寶寶想睡了' },
            { difficulty: 2, level: 'elementary', sentence: 'My friends ___ excited.', answer: 'are', options: ["is","are","am"], hint: '我的朋友很興奮' },
            { difficulty: 2, level: 'elementary', sentence: 'I am ___ today.', answer: 'sad', options: ["sad","sadly","sadness"], hint: '我今天難過' },
            { difficulty: 3, level: 'junior', sentence: 'I am ___ than you are.', answer: 'calmer', options: ["calm","calmer","calmest"], hint: '我比你冷靜' },
            { difficulty: 3, level: 'junior', sentence: 'He ___ very angry yesterday.', answer: 'was', options: ["is","was","were"], hint: '他昨天很生氣' },
            { difficulty: 3, level: 'junior', sentence: 'They ___ never been so happy.', answer: 'have', options: ["have","has","had"], hint: '他們從未這麼開心' },
        ],
    },
    {
        id: 'numbers', name: 'Numbers', emoji: '🔢', color: '#1ABC9C',
        unlocked: true,
        words: [
            { word: 'zero', emoji: '0️⃣', hint: '零' },
            { word: 'one', emoji: '1️⃣', hint: '一' },
            { word: 'two', emoji: '2️⃣', hint: '二' },
            { word: 'three', emoji: '3️⃣', hint: '三' },
            { word: 'four', emoji: '4️⃣', hint: '四' },
            { word: 'five', emoji: '5️⃣', hint: '五' },
            { word: 'six', emoji: '6️⃣', hint: '六' },
            { word: 'seven', emoji: '7️⃣', hint: '七' },
            { word: 'eight', emoji: '8️⃣', hint: '八' },
            { word: 'nine', emoji: '9️⃣', hint: '九' },
            { word: 'ten', emoji: '🔟', hint: '十' },
            { word: 'twenty', emoji: '🔢', hint: '二十' },
            { word: 'fifty', emoji: '🔢', hint: '五十' },
            { word: 'hundred', emoji: '💯', hint: '一百' },
            { word: 'first', emoji: '🥇', hint: '第一' },
            { word: 'second', emoji: '🥈', hint: '第二' },
            { word: 'third', emoji: '🥉', hint: '第三' },
            { word: 'last', emoji: '🏁', hint: '最後' },
        ],
        grammar: [
            { difficulty: 1, level: 'elementary', sentence: 'I have ___ apples.', answer: 'three', options: ['two', 'three', 'four'], hint: '我有三顆蘋果' },
            { difficulty: 1, level: 'elementary', sentence: 'She is ___ years old.', answer: 'ten', options: ['ten', 'hundred', 'first'], hint: '她十歲' },
            { difficulty: 1, level: 'elementary', sentence: 'Count from one ___ ten.', answer: 'to', options: ['to', 'at', 'in'], hint: '從一數到十' },
            { difficulty: 1, level: 'elementary', sentence: 'I see ___ cat.', answer: 'one', options: ['one', 'two', 'three'], hint: '我看到一隻貓' },
            { difficulty: 1, level: 'elementary', sentence: 'We are ___ friends.', answer: 'two', options: ['one', 'two', 'a'], hint: '我們是兩個朋友' },
            { difficulty: 2, level: 'elementary', sentence: 'There ___ five birds.', answer: 'are', options: ['is', 'are', 'am'], hint: '有五隻鳥' },
            { difficulty: 2, level: 'elementary', sentence: 'He has ___ books.', answer: 'many', options: ['many', 'much', 'lots'], hint: '他有很多書' },
            { difficulty: 2, level: 'elementary', sentence: 'I am ___ in line.', answer: 'first', options: ['one', 'first', 'second'], hint: '我是第一個排隊的' },
            { difficulty: 2, level: 'elementary', sentence: 'Give me ___ apples, please.', answer: 'three', options: ['three', 'third', 'a'], hint: '請給我三顆蘋果' },
            { difficulty: 3, level: 'junior', sentence: 'This box has ___ candies than that one.', answer: 'more', options: ['more', 'many', 'much'], hint: '這盒比那盒糖果更多' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ ten dollars yesterday.', answer: 'had', options: ['have', 'had', 'having'], hint: '我昨天有十元' },
            { difficulty: 3, level: 'junior', sentence: 'He came in ___ place.', answer: 'first', options: ['one', 'first', 'third'], hint: '他得到第一名' },
            { difficulty: 1, level: 'elementary', sentence: 'I have ___ pencils.', answer: 'ten', options: ["five","ten","twenty"], hint: '我有十支鉛筆' },
            { difficulty: 2, level: 'elementary', sentence: 'He is ___ in the race.', answer: 'first', options: ["one","first","second"], hint: '他在比賽中是第一' },
            { difficulty: 2, level: 'elementary', sentence: '___ many cats are there?', answer: 'How', options: ["How","What","Where"], hint: '有幾隻貓？' },
            { difficulty: 3, level: 'junior', sentence: 'This book has ___ pages than that one.', answer: 'more', options: ["more","many","much"], hint: '這本書頁數比那本多' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ ten dollars in my pocket.', answer: 'had', options: ["have","has","had"], hint: '我口袋有十元' },
            { difficulty: 3, level: 'junior', sentence: 'They ___ already won three times.', answer: 'have', options: ["have","has","had"], hint: '他們已經贏了三次' },
        ],
    },
    {
        id: 'hobbies', name: 'Hobbies', emoji: '🎨', color: '#E91E63',
        unlocked: true,
        words: [
            { word: 'read', emoji: '📚', hint: '閱讀' },
            { word: 'sing', emoji: '🎤', hint: '唱歌' },
            { word: 'dance', emoji: '💃', hint: '跳舞' },
            { word: 'swim', emoji: '🏊', hint: '游泳' },
            { word: 'run', emoji: '🏃', hint: '跑步' },
            { word: 'paint', emoji: '🎨', hint: '畫畫' },
            { word: 'draw', emoji: '🖌️', hint: '繪圖' },
            { word: 'cook', emoji: '👨‍🍳', hint: '煮飯' },
            { word: 'write', emoji: '📝', hint: '寫字' },
            { word: 'play', emoji: '🎮', hint: '玩' },
            { word: 'walk', emoji: '🚶', hint: '走路' },
            { word: 'ride', emoji: '🚴', hint: '騎車' },
            { word: 'jump', emoji: '🤸', hint: '跳' },
            { word: 'ski', emoji: '⛷️', hint: '滑雪' },
            { word: 'hike', emoji: '🥾', hint: '健行' },
            { word: 'shop', emoji: '🛍️', hint: '購物' },
            { word: 'travel', emoji: '✈️', hint: '旅行' },
            { word: 'yoga', emoji: '🧘', hint: '瑜珈' },
        ],
        grammar: [
            { difficulty: 1, level: 'elementary', sentence: 'I love to ___.', answer: 'read', options: ['read', 'reads', 'reading'], hint: '我愛閱讀' },
            { difficulty: 1, level: 'elementary', sentence: 'She can ___.', answer: 'sing', options: ['sing', 'sings', 'singing'], hint: '她會唱歌' },
            { difficulty: 1, level: 'elementary', sentence: 'We ___ to play games.', answer: 'love', options: ['love', 'loves', 'loving'], hint: '我們愛玩遊戲' },
            { difficulty: 1, level: 'elementary', sentence: 'He ___ to paint.', answer: 'likes', options: ['like', 'likes', 'liking'], hint: '他喜歡畫畫' },
            { difficulty: 1, level: 'elementary', sentence: 'I want to ___.', answer: 'dance', options: ['dance', 'dances', 'danced'], hint: '我想跳舞' },
            { difficulty: 2, level: 'elementary', sentence: 'They ___ swimming now.', answer: 'are', options: ['is', 'are', 'am'], hint: '他們正在游泳' },
            { difficulty: 2, level: 'elementary', sentence: 'I am ___ a book.', answer: 'reading', options: ['read', 'reads', 'reading'], hint: '我正在讀書' },
            { difficulty: 2, level: 'elementary', sentence: '___ you like to dance?', answer: 'Do', options: ['Do', 'Does', 'Are'], hint: '你喜歡跳舞嗎？' },
            { difficulty: 2, level: 'elementary', sentence: 'She likes ___.', answer: 'cooking', options: ['cook', 'cooks', 'cooking'], hint: '她喜歡煮飯' },
            { difficulty: 3, level: 'junior', sentence: 'He runs ___ than I do.', answer: 'faster', options: ['fast', 'faster', 'fastest'], hint: '他跑得比我快' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ a song last night.', answer: 'sang', options: ['sing', 'sang', 'sung'], hint: '我昨晚唱了一首歌' },
            { difficulty: 3, level: 'junior', sentence: 'We ___ to the park yesterday.', answer: 'walked', options: ['walk', 'walked', 'walking'], hint: '我們昨天走去公園' },
            { difficulty: 1, level: 'elementary', sentence: 'I can ___.', answer: 'jump', options: ["jump","jumps","jumping"], hint: '我會跳' },
            { difficulty: 2, level: 'elementary', sentence: 'She ___ swimming now.', answer: 'is', options: ["is","are","am"], hint: '她正在游泳' },
            { difficulty: 2, level: 'elementary', sentence: 'Do you like ___?', answer: 'cooking', options: ["cook","cooking","cooked"], hint: '你喜歡煮飯嗎？' },
            { difficulty: 3, level: 'junior', sentence: 'He swims ___ than I do.', answer: 'better', options: ["good","better","best"], hint: '他游得比我好' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ a picture last week.', answer: 'drew', options: ["draw","drew","drawn"], hint: '我上週畫了一張畫' },
            { difficulty: 3, level: 'junior', sentence: 'She ___ traveled to Japan.', answer: 'has', options: ["have","has","had"], hint: '她去過日本' },
        ],
    },
    {
        id: 'body', name: 'Body', emoji: '💪', color: '#FF7F50',
        unlocked: true,
        words: [
            { word: 'head', emoji: '🧠', hint: '頭' },
            { word: 'hair', emoji: '💇', hint: '頭髮' },
            { word: 'face', emoji: '😀', hint: '臉' },
            { word: 'eye', emoji: '👁️', hint: '眼睛' },
            { word: 'ear', emoji: '👂', hint: '耳朵' },
            { word: 'nose', emoji: '👃', hint: '鼻子' },
            { word: 'mouth', emoji: '👄', hint: '嘴巴' },
            { word: 'tooth', emoji: '🦷', hint: '牙齒' },
            { word: 'hand', emoji: '✋', hint: '手' },
            { word: 'arm', emoji: '💪', hint: '手臂' },
            { word: 'leg', emoji: '🦵', hint: '腿' },
            { word: 'foot', emoji: '🦶', hint: '腳' },
            { word: 'finger', emoji: '👆', hint: '手指' },
            { word: 'knee', emoji: '🦵', hint: '膝蓋' },
            { word: 'neck', emoji: '🧣', hint: '脖子' },
            { word: 'shoulder', emoji: '👤', hint: '肩膀' },
            { word: 'back', emoji: '🔙', hint: '背' },
            { word: 'body', emoji: '🧍', hint: '身體' },
        ],
        grammar: [
            { difficulty: 1, level: 'elementary', sentence: 'I have two ___.', answer: 'eyes', options: ['eye', 'eyes', 'eying'], hint: '我有兩隻眼睛' },
            { difficulty: 1, level: 'elementary', sentence: 'My ___ is long.', answer: 'hair', options: ['hair', 'hairs', 'haired'], hint: '我的頭髮很長' },
            { difficulty: 1, level: 'elementary', sentence: 'He has a big ___.', answer: 'nose', options: ['nose', 'noses', 'nosed'], hint: '他有大鼻子' },
            { difficulty: 1, level: 'elementary', sentence: 'Touch your ___.', answer: 'head', options: ['head', 'heads', 'heading'], hint: '摸你的頭' },
            { difficulty: 1, level: 'elementary', sentence: 'I see with my ___.', answer: 'eyes', options: ['ears', 'eyes', 'mouth'], hint: '我用眼睛看' },
            { difficulty: 2, level: 'elementary', sentence: 'She is brushing her ___.', answer: 'teeth', options: ['tooth', 'teeth', 'tooths'], hint: '她正在刷牙' },
            { difficulty: 2, level: 'elementary', sentence: 'I ___ my hands every day.', answer: 'wash', options: ['wash', 'washes', 'washing'], hint: '我每天洗手' },
            { difficulty: 2, level: 'elementary', sentence: 'My feet ___ tired.', answer: 'are', options: ['is', 'are', 'am'], hint: '我的腳很累' },
            { difficulty: 2, level: 'elementary', sentence: '___ many fingers do you have?', answer: 'How', options: ['What', 'How', 'Why'], hint: '你有幾隻手指？' },
            { difficulty: 3, level: 'junior', sentence: 'My hair is ___ than yours.', answer: 'longer', options: ['long', 'longer', 'longest'], hint: '我的頭髮比你長' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ my arm yesterday.', answer: 'hurt', options: ['hurt', 'hurts', 'hurting'], hint: '我昨天傷了手臂' },
            { difficulty: 3, level: 'junior', sentence: 'She ___ been sick for a week.', answer: 'has', options: ['have', 'has', 'having'], hint: '她已經生病一週了' },
            { difficulty: 1, level: 'elementary', sentence: 'I have one ___.', answer: 'mouth', options: ["mouth","mouths","mouthing"], hint: '我有一張嘴' },
            { difficulty: 2, level: 'elementary', sentence: 'His ___ are big.', answer: 'eyes', options: ["eye","eyes","eying"], hint: '他眼睛大' },
            { difficulty: 2, level: 'elementary', sentence: 'Her hair ___ black.', answer: 'is', options: ["is","are","am"], hint: '她頭髮是黑的' },
            { difficulty: 3, level: 'junior', sentence: 'My legs are ___ than my arms.', answer: 'longer', options: ["long","longer","longest"], hint: '我的腿比手臂長' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ my knee yesterday.', answer: 'hurt', options: ["hurt","hurts","hurting"], hint: '我昨天傷了膝蓋' },
            { difficulty: 3, level: 'junior', sentence: 'The dentist ___ my tooth.', answer: 'fixed', options: ["fix","fixed","fixing"], hint: '牙醫幫我修了牙齒' },
        ],
    },
    {
        id: 'clothes', name: 'Clothes', emoji: '👕', color: '#5D6D7E',
        unlocked: true,
        words: [
            { word: 'shirt', emoji: '👔', hint: '襯衫' },
            { word: 'pants', emoji: '👖', hint: '長褲' },
            { word: 'dress', emoji: '👗', hint: '洋裝' },
            { word: 'hat', emoji: '🎩', hint: '帽子' },
            { word: 'shoes', emoji: '👟', hint: '鞋子' },
            { word: 'socks', emoji: '🧦', hint: '襪子' },
            { word: 'jacket', emoji: '🧥', hint: '夾克' },
            { word: 'coat', emoji: '🧥', hint: '外套' },
            { word: 'shorts', emoji: '🩳', hint: '短褲' },
            { word: 'skirt', emoji: '👗', hint: '裙子' },
            { word: 'sweater', emoji: '🧶', hint: '毛衣' },
            { word: 'scarf', emoji: '🧣', hint: '圍巾' },
            { word: 'gloves', emoji: '🧤', hint: '手套' },
            { word: 'jeans', emoji: '👖', hint: '牛仔褲' },
            { word: 'uniform', emoji: '👕', hint: '制服' },
            { word: 'boots', emoji: '🥾', hint: '靴子' },
            { word: 'tie', emoji: '👔', hint: '領帶' },
            { word: 'cap', emoji: '🧢', hint: '鴨舌帽' },
        ],
        grammar: [
            { difficulty: 1, level: 'elementary', sentence: 'I am wearing a ___.', answer: 'hat', options: ['hat', 'hats', 'hatted'], hint: '我戴著一頂帽子' },
            { difficulty: 1, level: 'elementary', sentence: 'Her dress ___ pretty.', answer: 'is', options: ['is', 'are', 'am'], hint: '她的洋裝很漂亮' },
            { difficulty: 1, level: 'elementary', sentence: 'These shoes ___ new.', answer: 'are', options: ['is', 'are', 'am'], hint: '這雙鞋是新的' },
            { difficulty: 1, level: 'elementary', sentence: 'I like your ___.', answer: 'jacket', options: ['jacket', 'jackets', 'jacketed'], hint: '我喜歡你的夾克' },
            { difficulty: 1, level: 'elementary', sentence: 'Put on your ___.', answer: 'coat', options: ['coat', 'coats', 'coated'], hint: '穿上你的外套' },
            { difficulty: 2, level: 'elementary', sentence: 'He has ___ red shirt.', answer: 'a', options: ['a', 'an', 'the'], hint: '他有一件紅襯衫' },
            { difficulty: 2, level: 'elementary', sentence: '___ are my socks.', answer: 'These', options: ['This', 'These', 'That'], hint: '這些是我的襪子' },
            { difficulty: 2, level: 'elementary', sentence: 'She is ___ a beautiful dress.', answer: 'wearing', options: ['wear', 'wears', 'wearing'], hint: '她穿著一件漂亮的洋裝' },
            { difficulty: 2, level: 'elementary', sentence: 'My pants ___ too small.', answer: 'are', options: ['is', 'are', 'am'], hint: '我的褲子太小了' },
            { difficulty: 3, level: 'junior', sentence: 'This jacket is ___ than that one.', answer: 'warmer', options: ['warm', 'warmer', 'warmest'], hint: '這件夾克比那件暖' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ my new boots yesterday.', answer: 'wore', options: ['wear', 'wore', 'worn'], hint: '我昨天穿了新靴子' },
            { difficulty: 3, level: 'junior', sentence: '___ should I wear today?', answer: 'What', options: ['Who', 'What', 'Where'], hint: '我今天該穿什麼？' },
            { difficulty: 1, level: 'elementary', sentence: 'The ___ is on the bed.', answer: 'shirt', options: ["shirt","shirts","shirting"], hint: '襯衫在床上' },
            { difficulty: 2, level: 'elementary', sentence: 'She is ___ a coat.', answer: 'wearing', options: ["wear","wears","wearing"], hint: '她穿著外套' },
            { difficulty: 2, level: 'elementary', sentence: '___ is my hat?', answer: 'Where', options: ["What","Where","How"], hint: '我的帽子在哪裡？' },
            { difficulty: 3, level: 'junior', sentence: 'These boots are ___ than those shoes.', answer: 'heavier', options: ["heavy","heavier","heaviest"], hint: '這雙靴子比那雙鞋重' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ my uniform yesterday.', answer: 'washed', options: ["wash","washes","washed"], hint: '我昨天洗了制服' },
            { difficulty: 3, level: 'junior', sentence: 'He ___ never worn a tie.', answer: 'has', options: ["have","has","had"], hint: '他從沒戴過領帶' },
        ],
    },
    {
        id: 'weather', name: 'Weather', emoji: '🌤️', color: '#00BCD4',
        unlocked: true,
        words: [
            { word: 'sunny', emoji: '☀️', hint: '晴朗' },
            { word: 'rainy', emoji: '🌧️', hint: '下雨' },
            { word: 'cloudy', emoji: '☁️', hint: '多雲' },
            { word: 'snowy', emoji: '❄️', hint: '下雪' },
            { word: 'windy', emoji: '💨', hint: '有風' },
            { word: 'rain', emoji: '🌧️', hint: '雨' },
            { word: 'snow', emoji: '☃️', hint: '雪' },
            { word: 'wind', emoji: '🌬️', hint: '風' },
            { word: 'sun', emoji: '🌞', hint: '太陽' },
            { word: 'cloud', emoji: '☁️', hint: '雲' },
            { word: 'storm', emoji: '⛈️', hint: '暴風雨' },
            { word: 'fog', emoji: '🌫️', hint: '霧' },
            { word: 'ice', emoji: '🧊', hint: '冰' },
            { word: 'sky', emoji: '🌌', hint: '天空' },
            { word: 'rainbow', emoji: '🌈', hint: '彩虹' },
            { word: 'thunder', emoji: '⚡', hint: '雷' },
            { word: 'umbrella', emoji: '☂️', hint: '雨傘' },
            { word: 'season', emoji: '🍂', hint: '季節' },
        ],
        grammar: [
            { difficulty: 1, level: 'elementary', sentence: 'The sun ___ hot.', answer: 'is', options: ['is', 'are', 'am'], hint: '太陽很熱' },
            { difficulty: 1, level: 'elementary', sentence: 'It is ___ today.', answer: 'sunny', options: ['sun', 'sunny', 'sunshine'], hint: '今天天氣晴朗' },
            { difficulty: 1, level: 'elementary', sentence: 'I like ___ days.', answer: 'warm', options: ['warm', 'warmly', 'warmth'], hint: '我喜歡溫暖的天氣' },
            { difficulty: 1, level: 'elementary', sentence: 'It is ___. Take an umbrella.', answer: 'raining', options: ['rain', 'rains', 'raining'], hint: '在下雨。帶把傘' },
            { difficulty: 1, level: 'elementary', sentence: 'The sky is ___.', answer: 'blue', options: ['a blue', 'blue', 'blues'], hint: '天空是藍的' },
            { difficulty: 2, level: 'elementary', sentence: 'How ___ the weather today?', answer: 'is', options: ['is', 'are', 'am'], hint: '今天天氣如何？' },
            { difficulty: 2, level: 'elementary', sentence: 'It ___ snowing now.', answer: 'is', options: ['is', 'are', 'am'], hint: '正在下雪' },
            { difficulty: 2, level: 'elementary', sentence: 'The wind ___ blowing hard.', answer: 'is', options: ['is', 'are', 'am'], hint: '風很強' },
            { difficulty: 2, level: 'elementary', sentence: 'I love ___ days.', answer: 'sunny', options: ['sun', 'sunny', 'suns'], hint: '我喜愛晴天' },
            { difficulty: 3, level: 'junior', sentence: 'Today is ___ than yesterday.', answer: 'colder', options: ['cold', 'colder', 'coldest'], hint: '今天比昨天冷' },
            { difficulty: 3, level: 'junior', sentence: 'It ___ all day yesterday.', answer: 'rained', options: ['rain', 'rained', 'raining'], hint: '昨天整天下雨' },
            { difficulty: 3, level: 'junior', sentence: 'It ___ rain tomorrow.', answer: 'will', options: ['will', 'was', 'is'], hint: '明天會下雨' },
            { difficulty: 1, level: 'elementary', sentence: 'The ___ is warm.', answer: 'sun', options: ["sun","suns","sunny"], hint: '太陽很溫暖' },
            { difficulty: 2, level: 'elementary', sentence: 'It ___ very windy.', answer: 'is', options: ["is","are","am"], hint: '風很大' },
            { difficulty: 2, level: 'elementary', sentence: 'The clouds ___ in the sky.', answer: 'are', options: ["is","are","am"], hint: '雲在天空中' },
            { difficulty: 3, level: 'junior', sentence: 'Today is ___ than last week.', answer: 'warmer', options: ["warm","warmer","warmest"], hint: '今天比上週溫暖' },
            { difficulty: 3, level: 'junior', sentence: 'We ___ to the beach when it was sunny.', answer: 'went', options: ["go","went","gone"], hint: '天氣晴朗時我們去了海灘' },
            { difficulty: 3, level: 'junior', sentence: 'The storm ___ been strong this year.', answer: 'has', options: ["have","has","had"], hint: '今年的暴風雨很強' },
        ],
    },
    {
        id: 'time', name: 'Time', emoji: '🕐', color: '#34495E',
        unlocked: true,
        words: [
            { word: 'Monday', emoji: '📅', hint: '星期一' },
            { word: 'Tuesday', emoji: '📅', hint: '星期二' },
            { word: 'Wednesday', emoji: '📅', hint: '星期三' },
            { word: 'Thursday', emoji: '📅', hint: '星期四' },
            { word: 'Friday', emoji: '📅', hint: '星期五' },
            { word: 'Saturday', emoji: '📅', hint: '星期六' },
            { word: 'Sunday', emoji: '📅', hint: '星期日' },
            { word: 'morning', emoji: '🌅', hint: '早上' },
            { word: 'afternoon', emoji: '🌇', hint: '下午' },
            { word: 'evening', emoji: '🌆', hint: '傍晚' },
            { word: 'night', emoji: '🌙', hint: '晚上' },
            { word: 'today', emoji: '📆', hint: '今天' },
            { word: 'tomorrow', emoji: '➡️', hint: '明天' },
            { word: 'yesterday', emoji: '⬅️', hint: '昨天' },
            { word: 'week', emoji: '🗓️', hint: '一週' },
            { word: 'month', emoji: '📆', hint: '月' },
            { word: 'year', emoji: '🎊', hint: '年' },
            { word: 'hour', emoji: '⏰', hint: '小時' },
        ],
        grammar: [
            { difficulty: 1, level: 'elementary', sentence: 'Today is ___.', answer: 'Monday', options: ['Monday', 'morning', 'today'], hint: '今天是星期一' },
            { difficulty: 1, level: 'elementary', sentence: 'I get up in the ___.', answer: 'morning', options: ['morning', 'night', 'evening'], hint: '我早上起床' },
            { difficulty: 1, level: 'elementary', sentence: '___ is your birthday?', answer: 'When', options: ['When', 'Where', 'Who'], hint: '你的生日是什麼時候？' },
            { difficulty: 1, level: 'elementary', sentence: 'I go to bed at ___.', answer: 'night', options: ['morning', 'noon', 'night'], hint: '我晚上睡覺' },
            { difficulty: 1, level: 'elementary', sentence: 'I will see you ___.', answer: 'tomorrow', options: ['today', 'tomorrow', 'yesterday'], hint: '明天見' },
            { difficulty: 2, level: 'elementary', sentence: 'There ___ seven days in a week.', answer: 'are', options: ['is', 'are', 'am'], hint: '一週有七天' },
            { difficulty: 2, level: 'elementary', sentence: 'We have class on ___.', answer: 'Monday', options: ['Monday', 'morning', 'evening'], hint: '我們星期一有課' },
            { difficulty: 2, level: 'elementary', sentence: 'I ___ shopping yesterday.', answer: 'went', options: ['go', 'goes', 'went'], hint: '我昨天去購物' },
            { difficulty: 2, level: 'elementary', sentence: '___ is your favorite day?', answer: 'What', options: ['Who', 'What', 'Why'], hint: '你最喜歡哪一天？' },
            { difficulty: 3, level: 'junior', sentence: 'He ___ here last week.', answer: 'was', options: ['is', 'was', 'were'], hint: '他上週在這裡' },
            { difficulty: 3, level: 'junior', sentence: 'We ___ TV every evening.', answer: 'watch', options: ['watch', 'watches', 'watching'], hint: '我們每晚看電視' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ to school yesterday.', answer: 'went', options: ['go', 'went', 'gone'], hint: '我昨天去上學' },
            { difficulty: 1, level: 'elementary', sentence: '___ is the day after Monday.', answer: 'Tuesday', options: ["Sunday","Tuesday","Friday"], hint: '星期一之後是星期二' },
            { difficulty: 2, level: 'elementary', sentence: 'I have school ___ Monday.', answer: 'on', options: ["on","in","at"], hint: '我星期一上學' },
            { difficulty: 2, level: 'elementary', sentence: 'We are ___ class now.', answer: 'in', options: ["on","in","at"], hint: '我們現在在上課' },
            { difficulty: 3, level: 'junior', sentence: 'This week is ___ than last week.', answer: 'busier', options: ["busy","busier","busiest"], hint: '這週比上週忙' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ my homework last night.', answer: 'finished', options: ["finish","finished","finishing"], hint: '我昨晚寫完作業' },
            { difficulty: 3, level: 'junior', sentence: 'They ___ been here for a year.', answer: 'have', options: ["have","has","had"], hint: '他們在這裡一年了' },
        ],
    },
    {
        id: 'jobs', name: 'Jobs', emoji: '💼', color: '#FFC107',
        unlocked: true,
        words: [
            { word: 'nurse', emoji: '👩‍⚕️', hint: '護士' },
            { word: 'farmer', emoji: '👨‍🌾', hint: '農夫' },
            { word: 'cook', emoji: '👨‍🍳', hint: '廚師' },
            { word: 'driver', emoji: '🚖', hint: '司機' },
            { word: 'singer', emoji: '🎤', hint: '歌手' },
            { word: 'dancer', emoji: '💃', hint: '舞者' },
            { word: 'actor', emoji: '🎭', hint: '演員' },
            { word: 'painter', emoji: '🎨', hint: '畫家' },
            { word: 'writer', emoji: '✍️', hint: '作家' },
            { word: 'lawyer', emoji: '⚖️', hint: '律師' },
            { word: 'dentist', emoji: '🦷', hint: '牙醫' },
            { word: 'scientist', emoji: '🔬', hint: '科學家' },
            { word: 'soldier', emoji: '🪖', hint: '士兵' },
            { word: 'baker', emoji: '🥖', hint: '麵包師' },
            { word: 'waiter', emoji: '🤵', hint: '服務生' },
            { word: 'pilot', emoji: '✈️', hint: '飛行員' },
            { word: 'police', emoji: '👮', hint: '警察' },
            { word: 'engineer', emoji: '👷', hint: '工程師' },
        ],
        grammar: [
            { difficulty: 1, level: 'elementary', sentence: 'He ___ a doctor.', answer: 'is', options: ['is', 'are', 'am'], hint: '他是醫生' },
            { difficulty: 1, level: 'elementary', sentence: 'My uncle ___ a farmer.', answer: 'is', options: ['is', 'are', 'am'], hint: '我叔叔是農夫' },
            { difficulty: 1, level: 'elementary', sentence: 'She wants to be a ___.', answer: 'singer', options: ['sing', 'singer', 'sings'], hint: '她想當歌手' },
            { difficulty: 1, level: 'elementary', sentence: 'The ___ helps sick people.', answer: 'nurse', options: ['nurse', 'farmer', 'singer'], hint: '護士幫助病人' },
            { difficulty: 1, level: 'elementary', sentence: 'A pilot flies ___.', answer: 'planes', options: ['plane', 'planes', 'planing'], hint: '飛行員開飛機' },
            { difficulty: 2, level: 'elementary', sentence: 'My father ___ a writer.', answer: 'is', options: ['is', 'are', 'am'], hint: '我爸爸是作家' },
            { difficulty: 2, level: 'elementary', sentence: '___ does she do?', answer: 'What', options: ['What', 'Why', 'When'], hint: '她做什麼工作？' },
            { difficulty: 2, level: 'elementary', sentence: 'Doctors ___ in hospitals.', answer: 'work', options: ['work', 'works', 'working'], hint: '醫生在醫院工作' },
            { difficulty: 2, level: 'elementary', sentence: 'I want to ___ a singer.', answer: 'be', options: ['be', 'is', 'am'], hint: '我想成為歌手' },
            { difficulty: 3, level: 'junior', sentence: 'She ___ been a nurse for five years.', answer: 'has', options: ['have', 'has', 'had'], hint: '她當護士五年了' },
            { difficulty: 3, level: 'junior', sentence: 'He ___ a farmer when he was young.', answer: 'was', options: ['is', 'was', 'were'], hint: '他年輕時是農夫' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ to become a scientist.', answer: 'want', options: ['want', 'wants', 'wanted'], hint: '我想成為科學家' },
            { difficulty: 1, level: 'elementary', sentence: 'The cook ___ in the kitchen.', answer: 'works', options: ["work","works","working"], hint: '廚師在廚房工作' },
            { difficulty: 2, level: 'elementary', sentence: '___ is the teacher?', answer: 'Where', options: ["What","Where","How"], hint: '老師在哪裡？' },
            { difficulty: 2, level: 'elementary', sentence: 'My mom is ___ engineer.', answer: 'an', options: ["a","an","the"], hint: '我媽媽是工程師' },
            { difficulty: 3, level: 'junior', sentence: 'Doctors are ___ than nurses sometimes.', answer: 'busier', options: ["busy","busier","busiest"], hint: '醫生有時比護士忙' },
            { difficulty: 3, level: 'junior', sentence: 'He ___ a teacher for many years.', answer: 'was', options: ["is","was","were"], hint: '他當了多年老師' },
            { difficulty: 3, level: 'junior', sentence: 'She ___ become a writer.', answer: 'will', options: ["will","was","were"], hint: '她將成為作家' },
        ],
    },
    {
        id: 'places', name: 'Places', emoji: '🏙️', color: '#009688',
        unlocked: true,
        words: [
            { word: 'home', emoji: '🏠', hint: '家' },
            { word: 'library', emoji: '📚', hint: '圖書館' },
            { word: 'hospital', emoji: '🏥', hint: '醫院' },
            { word: 'park', emoji: '🌳', hint: '公園' },
            { word: 'store', emoji: '🏪', hint: '商店' },
            { word: 'market', emoji: '🛒', hint: '市場' },
            { word: 'restaurant', emoji: '🍽️', hint: '餐廳' },
            { word: 'bank', emoji: '🏦', hint: '銀行' },
            { word: 'museum', emoji: '🏛️', hint: '博物館' },
            { word: 'zoo', emoji: '🦒', hint: '動物園' },
            { word: 'cinema', emoji: '🎬', hint: '電影院' },
            { word: 'station', emoji: '🚉', hint: '車站' },
            { word: 'airport', emoji: '🛫', hint: '機場' },
            { word: 'beach', emoji: '🏖️', hint: '海灘' },
            { word: 'mountain', emoji: '⛰️', hint: '山' },
            { word: 'city', emoji: '🌆', hint: '城市' },
            { word: 'town', emoji: '🏘️', hint: '小鎮' },
            { word: 'farm', emoji: '🚜', hint: '農場' },
        ],
        grammar: [
            { difficulty: 1, level: 'elementary', sentence: 'I go to ___ every day.', answer: 'school', options: ['school', 'home', 'park'], hint: '我每天去學校' },
            { difficulty: 1, level: 'elementary', sentence: 'The library is ___ here.', answer: 'near', options: ['near', 'far', 'on'], hint: '圖書館在這附近' },
            { difficulty: 1, level: 'elementary', sentence: 'We are at ___.', answer: 'home', options: ['home', 'homes', 'homing'], hint: '我們在家' },
            { difficulty: 1, level: 'elementary', sentence: '___ is the park?', answer: 'Where', options: ['What', 'Where', 'Why'], hint: '公園在哪裡？' },
            { difficulty: 1, level: 'elementary', sentence: 'The zoo ___ beautiful.', answer: 'is', options: ['is', 'are', 'am'], hint: '動物園很美' },
            { difficulty: 2, level: 'elementary', sentence: 'There ___ many stores in town.', answer: 'are', options: ['is', 'are', 'am'], hint: '鎮上有很多商店' },
            { difficulty: 2, level: 'elementary', sentence: 'I ___ to the museum yesterday.', answer: 'went', options: ['go', 'went', 'going'], hint: '我昨天去博物館' },
            { difficulty: 2, level: 'elementary', sentence: 'The bank ___ at 9 am.', answer: 'opens', options: ['open', 'opens', 'opening'], hint: '銀行九點開門' },
            { difficulty: 2, level: 'elementary', sentence: 'Let us go ___ the park.', answer: 'to', options: ['to', 'at', 'in'], hint: '我們去公園吧' },
            { difficulty: 3, level: 'junior', sentence: 'The library is ___ than the bank.', answer: 'bigger', options: ['big', 'bigger', 'biggest'], hint: '圖書館比銀行大' },
            { difficulty: 3, level: 'junior', sentence: 'He ___ been to the airport.', answer: 'has', options: ['have', 'has', 'had'], hint: '他去過機場' },
            { difficulty: 3, level: 'junior', sentence: 'We ___ go to the beach tomorrow.', answer: 'will', options: ['will', 'was', 'are'], hint: '我們明天會去海灘' },
            { difficulty: 1, level: 'elementary', sentence: 'The cinema ___ near the park.', answer: 'is', options: ["is","are","am"], hint: '電影院在公園附近' },
            { difficulty: 2, level: 'elementary', sentence: 'We ___ shopping on Sunday.', answer: 'go', options: ["go","goes","going"], hint: '我們週日去購物' },
            { difficulty: 2, level: 'elementary', sentence: 'The hospital ___ very busy.', answer: 'is', options: ["is","are","am"], hint: '醫院很忙' },
            { difficulty: 3, level: 'junior', sentence: 'The mountain is ___ than the hill.', answer: 'taller', options: ["tall","taller","tallest"], hint: '山比丘陵高' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ to the airport yesterday.', answer: 'drove', options: ["drive","drove","driven"], hint: '我昨天開車去機場' },
            { difficulty: 3, level: 'junior', sentence: 'We ___ visited Tokyo.', answer: 'have', options: ["have","has","had"], hint: '我們去過東京' },
        ],
    },
    {
        id: 'transport', name: 'Transport', emoji: '🚗', color: '#607D8B',
        unlocked: true,
        words: [
            { word: 'car', emoji: '🚗', hint: '汽車' },
            { word: 'bus', emoji: '🚌', hint: '公車' },
            { word: 'train', emoji: '🚆', hint: '火車' },
            { word: 'plane', emoji: '✈️', hint: '飛機' },
            { word: 'bike', emoji: '🚲', hint: '腳踏車' },
            { word: 'boat', emoji: '⛵', hint: '小船' },
            { word: 'ship', emoji: '🚢', hint: '輪船' },
            { word: 'truck', emoji: '🚚', hint: '卡車' },
            { word: 'taxi', emoji: '🚕', hint: '計程車' },
            { word: 'scooter', emoji: '🛵', hint: '機車' },
            { word: 'subway', emoji: '🚇', hint: '地鐵' },
            { word: 'helicopter', emoji: '🚁', hint: '直升機' },
            { word: 'rocket', emoji: '🚀', hint: '火箭' },
            { word: 'wheel', emoji: '☸️', hint: '輪子' },
            { word: 'road', emoji: '🛣️', hint: '馬路' },
            { word: 'bridge', emoji: '🌉', hint: '橋' },
            { word: 'ticket', emoji: '🎫', hint: '車票' },
            { word: 'tire', emoji: '🛞', hint: '輪胎' },
        ],
        grammar: [
            { difficulty: 1, level: 'elementary', sentence: 'I take the ___ to school.', answer: 'bus', options: ['bus', 'cup', 'book'], hint: '我搭公車上學' },
            { difficulty: 1, level: 'elementary', sentence: 'A ___ flies in the sky.', answer: 'plane', options: ['car', 'plane', 'boat'], hint: '飛機在天上飛' },
            { difficulty: 1, level: 'elementary', sentence: 'He ___ his bike.', answer: 'rides', options: ['ride', 'rides', 'riding'], hint: '他騎腳踏車' },
            { difficulty: 1, level: 'elementary', sentence: 'The car ___ fast.', answer: 'is', options: ['is', 'are', 'am'], hint: '車子很快' },
            { difficulty: 1, level: 'elementary', sentence: 'We go by ___.', answer: 'train', options: ['train', 'trains', 'training'], hint: '我們搭火車' },
            { difficulty: 2, level: 'elementary', sentence: '___ do you go to school?', answer: 'How', options: ['How', 'Why', 'When'], hint: '你怎麼去學校？' },
            { difficulty: 2, level: 'elementary', sentence: 'I ___ to school by bus.', answer: 'go', options: ['go', 'goes', 'going'], hint: '我搭公車上學' },
            { difficulty: 2, level: 'elementary', sentence: 'The plane ___ at 8 am.', answer: 'arrives', options: ['arrive', 'arrives', 'arriving'], hint: '飛機八點抵達' },
            { difficulty: 2, level: 'elementary', sentence: 'There ___ many cars on the road.', answer: 'are', options: ['is', 'are', 'am'], hint: '路上有很多車' },
            { difficulty: 3, level: 'junior', sentence: 'A train is ___ than a car.', answer: 'faster', options: ['fast', 'faster', 'fastest'], hint: '火車比車子快' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ a bus to school yesterday.', answer: 'took', options: ['take', 'took', 'taken'], hint: '我昨天搭公車上學' },
            { difficulty: 3, level: 'junior', sentence: 'We ___ travel by plane next week.', answer: 'will', options: ['will', 'was', 'were'], hint: '我們下週要搭飛機' },
            { difficulty: 1, level: 'elementary', sentence: 'The ___ is fast.', answer: 'train', options: ["train","trains","training"], hint: '火車很快' },
            { difficulty: 2, level: 'elementary', sentence: 'The plane ___ in the sky.', answer: 'is', options: ["is","are","am"], hint: '飛機在天上' },
            { difficulty: 2, level: 'elementary', sentence: 'I ___ a new bike.', answer: 'have', options: ["has","have","having"], hint: '我有一台新腳踏車' },
            { difficulty: 3, level: 'junior', sentence: 'My bike is ___ than yours.', answer: 'newer', options: ["new","newer","newest"], hint: '我的腳踏車比你的新' },
            { difficulty: 3, level: 'junior', sentence: 'He ___ his motorcycle yesterday.', answer: 'rode', options: ["ride","rode","ridden"], hint: '他昨天騎機車' },
            { difficulty: 3, level: 'junior', sentence: 'They ___ already bought tickets.', answer: 'have', options: ["have","has","had"], hint: '他們已經買好票了' },
        ],
    },
    {
        id: 'sports', name: 'Sports', emoji: '⚽', color: '#FF5722',
        unlocked: true,
        words: [
            { word: 'soccer', emoji: '⚽', hint: '足球' },
            { word: 'basketball', emoji: '🏀', hint: '籃球' },
            { word: 'baseball', emoji: '⚾', hint: '棒球' },
            { word: 'tennis', emoji: '🎾', hint: '網球' },
            { word: 'volleyball', emoji: '🏐', hint: '排球' },
            { word: 'golf', emoji: '⛳', hint: '高爾夫' },
            { word: 'hockey', emoji: '🏒', hint: '曲棍球' },
            { word: 'boxing', emoji: '🥊', hint: '拳擊' },
            { word: 'badminton', emoji: '🏸', hint: '羽毛球' },
            { word: 'surfing', emoji: '🏄', hint: '衝浪' },
            { word: 'skating', emoji: '⛸️', hint: '溜冰' },
            { word: 'climbing', emoji: '🧗', hint: '攀岩' },
            { word: 'skiing', emoji: '⛷️', hint: '滑雪' },
            { word: 'jogging', emoji: '🏃', hint: '慢跑' },
            { word: 'cycling', emoji: '🚴', hint: '自行車' },
            { word: 'archery', emoji: '🏹', hint: '射箭' },
            { word: 'rugby', emoji: '🏉', hint: '橄欖球' },
            { word: 'bowling', emoji: '🎳', hint: '保齡球' },
        ],
        grammar: [
            { difficulty: 1, level: 'elementary', sentence: 'I like ___.', answer: 'soccer', options: ['soccer', 'soccers', 'soccering'], hint: '我喜歡足球' },
            { difficulty: 1, level: 'elementary', sentence: 'He plays ___.', answer: 'basketball', options: ['basketball', 'basketballs', 'basketballing'], hint: '他打籃球' },
            { difficulty: 1, level: 'elementary', sentence: 'We ___ tennis.', answer: 'play', options: ['play', 'plays', 'playing'], hint: '我們打網球' },
            { difficulty: 1, level: 'elementary', sentence: 'Swimming is ___.', answer: 'fun', options: ['fun', 'funs', 'funny'], hint: '游泳很有趣' },
            { difficulty: 1, level: 'elementary', sentence: '___ is your favorite sport?', answer: 'What', options: ['What', 'When', 'Why'], hint: '你最喜歡的運動是什麼？' },
            { difficulty: 2, level: 'elementary', sentence: 'They ___ baseball every weekend.', answer: 'play', options: ['play', 'plays', 'playing'], hint: '他們每週末打棒球' },
            { difficulty: 2, level: 'elementary', sentence: 'She ___ very well.', answer: 'swims', options: ['swim', 'swims', 'swimming'], hint: '她游得很好' },
            { difficulty: 2, level: 'elementary', sentence: 'We are ___ a game now.', answer: 'playing', options: ['play', 'plays', 'playing'], hint: '我們正在比賽' },
            { difficulty: 2, level: 'elementary', sentence: '___ basketball is fun.', answer: 'Playing', options: ['Play', 'Plays', 'Playing'], hint: '打籃球很有趣' },
            { difficulty: 3, level: 'junior', sentence: 'Soccer is ___ than tennis.', answer: 'harder', options: ['hard', 'harder', 'hardest'], hint: '足球比網球難' },
            { difficulty: 3, level: 'junior', sentence: 'He ___ tennis last week.', answer: 'played', options: ['play', 'plays', 'played'], hint: '他上週打網球' },
            { difficulty: 3, level: 'junior', sentence: 'They ___ won three games.', answer: 'have', options: ['have', 'has', 'having'], hint: '他們已經贏了三場' },
            { difficulty: 1, level: 'elementary', sentence: 'He ___ tennis well.', answer: 'plays', options: ["play","plays","playing"], hint: '他網球打得好' },
            { difficulty: 2, level: 'elementary', sentence: 'Volleyball ___ fun.', answer: 'is', options: ["is","are","am"], hint: '排球很有趣' },
            { difficulty: 2, level: 'elementary', sentence: 'We ___ at the gym now.', answer: 'are', options: ["is","are","am"], hint: '我們現在在健身房' },
            { difficulty: 3, level: 'junior', sentence: 'This game is ___ than that one.', answer: 'longer', options: ["long","longer","longest"], hint: '這場比那場長' },
            { difficulty: 3, level: 'junior', sentence: 'I ___ rugby last weekend.', answer: 'played', options: ["play","plays","played"], hint: '我上週末打橄欖球' },
            { difficulty: 3, level: 'junior', sentence: 'She ___ never tried surfing.', answer: 'has', options: ["have","has","had"], hint: '她從沒衝過浪' },
        ],
    }
    ]
};

// Return themes filtered for a learner level.
//   forLevel('elementary') -> only elementary grammar (Grades 3-6 friendly).
//   forLevel('junior')     -> all grammar (junior includes elementary content).
//   forLevel()             -> raw themes, no filtering.
window.QUESTION_BANK.forLevel = function (level) {
    if (level !== 'elementary' && level !== 'junior') return this.themes;
    const allowed = level === 'junior'
        ? new Set(['elementary', 'junior'])
        : new Set(['elementary']);
    return this.themes.map(t => ({
        ...t,
        grammar: t.grammar.filter(g => allowed.has(g.level || 'junior')),
    }));
};
